# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 02:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20180528_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.Book'),
            preserve_default=False,
        ),
    ]
