# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180529_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.FileField(upload_to=b''),
        ),
    ]
