# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-13 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_remove_question_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.FileField(default='/media/icon8.png', upload_to=b''),
            preserve_default=False,
        ),
    ]
