# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=250)),
                ('comment', models.CharField(max_length=4000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Question')),
            ],
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='AnswerComment',
        ),
    ]
